stages:
  - build
  - test
  - deploy

build website:
  stage: build
  script: 
    - SET NODE_EXTRA_CA_CERTS=C:\Trainings\zScalerRootCertificate.cer
    - SET NODE_TLS_REJECT_UNAUTHORIZED=0
    - call npm config set strict-ssl=false
    - call npm config set cafile C:\Trainings\zScalerRootCertificate.cer
    - echo %CI_COMMIT_SHORT_SHA%
    - call npm install
    - call npm install -g gatsby-cli
    - gatsby build
    - sed -i 's|%%VERSION%%|%CI_COMMIT_SHORT_SHA%|' .\\public\\index.html

  artifacts:
    paths:
      - ".\\public"
      - ".\\.cache"

test artifact:
  stage: test 
  script:
    - grep -q "Gatsby" .\\public\\index.html

# test website:
#  stage: test
#  script:
#    - SET NODE_EXTRA_CA_CERTS=C:\Trainings\zScalerRootCertificate.cer
#    - SET NODE_TLS_REJECT_UNAUTHORIZED=0
#    - call npm config set strict-ssl=false
#    - call npm config set cafile C:\Trainings\zScalerRootCertificate.cer
#    - call npm install
#    - call npm install -g gatsby-cli
#    - START /B "" gatsby serve --port 9001 
#    - sleep 30
#    - curl "http://localhost:9001" | tac | tac | grep -q "Gatsby"

deploy to surge:
  stage: deploy
  script:
    - call npm install --global surge
    - surge --project ./public --domain sweet-answer.surge.sh