build website:
  script: 
    - SET NODE_EXTRA_CA_CERTS="C:\Trainings\zScalerRootCertificate.cer"
    - SET NODE_TLS_REJECT_UNAUTHORIZED=0
    - npm config set strict-ssl=false
    - npm config set cafile "C:\Trainings\zScalerRootCertificate.cer"
    - npm install
    - npm install -g gatsby-cli
    - gatsby build